services:
  - type: web
    name: ylsh-backend
    runtime: node
    rootDir: backend
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
