import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Auth, Identity, and RBAC',
    rating: 5,
    ratingCount: 8,
    price: 0,
    category: 'Phase 1',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Event Management and Registration',
    rating: 5,
    ratingCount: 15,
    price: 0,
    category: 'Phase 1',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Attendance, QR Scans, and Fraud Checks',
    rating: 4,
    ratingCount: 7,
    price: 0,
    category: 'Phase 1',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Certificate Engine and Verification',
    rating: 4,
    ratingCount: 12,
    price: 0,
    category: 'Phase 1',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'Opportunities: Jobs, Grants, Scholarships',
    rating: 4,
    ratingCount: 32,
    price: 0,
    category: 'Phase 2',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Mentorship Discovery, Booking, and Reminders',
    rating: 5,
    ratingCount: 14,
    price: 0,
    category: 'Phase 2',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Analytics and Deployment Readiness',
    rating: 4,
    ratingCount: 6,
    price: 0,
    category: 'Phase 3',
  },
]
